// ============================================================================
// CarbonTrackAI — iXBRL Generator
// Generates Inline XBRL (iXBRL) documents per ESEF requirements using the
// EFRAG ESRS XBRL taxonomy for CSRD compliance.
// ============================================================================

const ESRS_NAMESPACE = "http://efrag.org/esrs/2024/esrs";
const IX_NAMESPACE = "http://www.xbrl.org/2013/inlineXBRL";
const XHTML_NAMESPACE = "http://www.w3.org/1999/xhtml";
const XBRLI_NAMESPACE = "http://www.xbrl.org/2013/inlineXBRL";

export interface XbrlDatapoint {
  tag: string;           // e.g. "esrs_E1-6-Scope1GHGEmissions"
  value: string | number;
  unit?: string;         // e.g. "tCO2e", "MWh", "EUR"
  label: string;
  dataType: "numeric" | "percentage" | "boolean" | "narrative";
  decimals?: number;
}

export interface IxbrlContext {
  entityName: string;
  entityIdentifier: string;  // LEI or national ID
  reportingYear: number;
  generatedAt: string;
}

/**
 * Generate a complete iXBRL document (XHTML with embedded XBRL tags).
 * Output is a valid XHTML document that renders in browsers and can be
 * processed by XBRL validators (Arelle, etc.).
 */
export function generateIxbrl(
  datapoints: XbrlDatapoint[],
  context: IxbrlContext,
): string {
  const { entityName, entityIdentifier, reportingYear, generatedAt } = context;

  return `<?xml version="1.0" encoding="UTF-8"?>
<html
  xmlns="${XHTML_NAMESPACE}"
  xmlns:ix="${IX_NAMESPACE}"
  xmlns:esrs="${ESRS_NAMESPACE}"
  xmlns:xbrli="${XBRLI_NAMESPACE}">
<head>
  <meta charset="UTF-8" />
  <title>ESG Report ${reportingYear} — ${escapeXml(entityName)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 1.8em; border-bottom: 2px solid #059669; padding-bottom: 8px; }
    h2 { font-size: 1.3em; color: #059669; margin-top: 2em; }
    table { width: 100%; border-collapse: collapse; margin: 1em 0; }
    th, td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; font-size: 0.9em; }
    th { background: #f9fafb; font-weight: 600; }
    .tagged { background: #f0fdf4; }
    .meta { color: #6b7280; font-size: 0.85em; margin-top: 2em; border-top: 1px solid #e5e7eb; padding-top: 1em; }
    .disclaimer { color: #9ca3af; font-size: 0.75em; margin-top: 0.5em; font-style: italic; }
  </style>
</head>
<body>
  <h1>ESG Sustainability Report ${reportingYear}</h1>
  <p><strong>Entity:</strong> ${escapeXml(entityName)}</p>
  <p><strong>Identifier:</strong> ${escapeXml(entityIdentifier)}</p>
  <p><strong>Reporting period:</strong> ${reportingYear}-01-01 to ${reportingYear}-12-31</p>
  <p class="disclaimer">This document contains Inline XBRL (iXBRL) tags per the ESRS XBRL taxonomy (EFRAG). The preparer remains responsible for the file submitted to the OAM.</p>

${generatePillarSections(datapoints, reportingYear)}

  <div class="meta">
    <p>Generated by CarbonTrackAI on ${generatedAt}</p>
    <p>XBRL taxonomy: ESRS Set 1 (EFRAG, ${ESRS_NAMESPACE})</p>
  </div>
</body>
</html>`;
}

// ─── Pillar section generation ────────────────────────────────────────────────

function generatePillarSections(datapoints: XbrlDatapoint[], year: number): string {
  const pillars = [
    { key: "E", title: "Environmental", icon: "🌍" },
    { key: "S", title: "Social", icon: "👥" },
    { key: "G", title: "Governance", icon: "🏛️" },
    { key: "ESRS", title: "Cross-Cutting", icon: "⚖️" },
  ];

  let html = "";

  for (const pillar of pillars) {
    const pillarDps = datapoints.filter((d) => d.tag.startsWith(`esrs_${pillar.key}`) || d.tag.includes(pillar.key));
    if (pillarDps.length === 0) continue;

    html += `
  <h2>${pillar.icon} ${pillar.title}</h2>
  <table>
    <thead><tr><th>Disclosure</th><th>Value</th><th>Unit</th></tr></thead>
    <tbody>`;

    for (const dp of pillarDps) {
      const tagContent = dp.dataType === "narrative"
        ? `<ix:nonNumeric name="esrs:${dp.tag}" contextRef="ctx-${year}" escape="true">${escapeXml(String(dp.value))}</ix:nonNumeric>`
        : dp.dataType === "percentage"
        ? `<ix:nonFraction name="esrs:${dp.tag}" contextRef="ctx-${year}" unitRef="pure" decimals="2" scale="0">${dp.value}</ix:nonFraction>`
        : `<ix:nonFraction name="esrs:${dp.tag}" contextRef="ctx-${year}" unitRef="${dp.unit || 'pure'}" decimals="${dp.decimals ?? 2}" scale="0">${dp.value}</ix:nonFraction>`;

      html += `
      <tr class="tagged">
        <td>${escapeXml(dp.label)}</td>
        <td>${tagContent}</td>
        <td>${dp.unit || "—"}</td>
      </tr>`;
    }

    html += `
    </tbody>
  </table>`;
  }

  return html;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// ─── Report data → iXBRL datapoints mapping ──────────────────────────────────

/**
 * Map CarbonTrackAI report data to iXBRL-taggable datapoints.
 * Uses the report_data JSON structure from Report Builder.
 */
export function mapReportToIxbrl(reportData: Record<string, any>): XbrlDatapoint[] {
  const dps: XbrlDatapoint[] = [];
  const meta = reportData.meta ?? {};
  const env = reportData.environmental ?? {};
  const soc = reportData.social ?? {};
  const gov = reportData.governance ?? {};

  // Environmental
  if (env.climate?.calculations?.scope1_tco2e != null) {
    dps.push({ tag: "esrs_E1-6-Scope1GHGEmissions", value: env.climate.calculations.scope1_tco2e, unit: "tCO2e", label: "Scope 1 GHG emissions", dataType: "numeric", decimals: 2 });
  }
  if (env.climate?.calculations?.scope2_tco2e != null) {
    dps.push({ tag: "esrs_E1-6-Scope2LocationBasedGHGEmissions", value: env.climate.calculations.scope2_tco2e, unit: "tCO2e", label: "Scope 2 GHG emissions (location-based)", dataType: "numeric", decimals: 2 });
  }
  if (env.climate?.calculations?.total_mwh != null) {
    dps.push({ tag: "esrs_E1-6-TotalEnergyConsumption", value: env.climate.calculations.total_mwh, unit: "MWh", label: "Total energy consumption", dataType: "numeric", decimals: 1 });
  }
  if (env.pollution?.pollutants != null) {
    dps.push({ tag: "esrs_E2-1-AirPollutantEmissions", value: env.pollution.pollutants, unit: "types", label: "Air pollutant types tracked", dataType: "numeric" });
  }
  if (env.water?.consumptionSources != null) {
    dps.push({ tag: "esrs_E3-1-WaterConsumptionVolume", value: env.water.consumptionSources, unit: "sources", label: "Water consumption sources", dataType: "numeric" });
  }
  if (env.biodiversity?.sites != null) {
    dps.push({ tag: "esrs_E4-2-SitesNearProtectedAreas", value: env.biodiversity.sites, unit: "sites", label: "Biodiversity sites assessed", dataType: "numeric" });
  }
  if (env.circularEconomy?.materialTypes != null) {
    dps.push({ tag: "esrs_E5-1-MaterialInputMass", value: env.circularEconomy.materialTypes, unit: "types", label: "Material types tracked", dataType: "numeric" });
  }
  if (env.circularEconomy?.wasteTypes != null) {
    dps.push({ tag: "esrs_E5-5-WasteByDisposalMethod", value: env.circularEconomy.wasteTypes, unit: "types", label: "Waste types tracked", dataType: "numeric" });
  }

  // Social
  if (soc.workforce?.headcount != null) {
    dps.push({ tag: "esrs_S1-6-TotalEmployeeHeadcount", value: soc.workforce.headcount, unit: "employees", label: "Total employee headcount", dataType: "numeric" });
  }
  if (soc.workforce?.payGap?.mean != null) {
    dps.push({ tag: "esrs_S1-16-GenderPayGap", value: soc.workforce.payGap.mean, unit: "%", label: "Gender pay gap (mean)", dataType: "percentage" });
  }
  if (soc.workforce?.healthSafety?.injuries != null) {
    dps.push({ tag: "esrs_S1-14-RecordableWorkRelatedInjuries", value: soc.workforce.healthSafety.injuries, unit: "incidents", label: "Recordable work-related injuries", dataType: "numeric" });
  }
  if (soc.workforce?.training?.totalHours != null) {
    dps.push({ tag: "esrs_S1-13-AverageTrainingHours", value: Number(soc.workforce.training.avgPerEmployee ?? 0), unit: "hours", label: "Average training hours per employee", dataType: "numeric", decimals: 1 });
  }
  if (soc.workforce?.turnover != null) {
    dps.push({ tag: "esrs_S1-6-EmployeeTurnoverRate", value: soc.workforce.turnover.leavers ?? 0, unit: "employees", label: "Employee turnover (leavers)", dataType: "numeric" });
  }

  // Governance
  if (gov.board?.size != null) {
    dps.push({ tag: "esrs_G1-1-BoardComposition", value: `${gov.board.size} members, ${gov.board.independentMembers} independent, ${gov.board.womenOnBoard} women`, label: "Board composition", dataType: "narrative" });
  }
  if (gov.complianceIncidents != null) {
    dps.push({ tag: "esrs_G1-4-ComplianceIncidents", value: gov.complianceIncidents, unit: "incidents", label: "Compliance incidents", dataType: "numeric" });
  }
  if (gov.dataBreaches != null) {
    dps.push({ tag: "esrs_G1-5-DataBreaches", value: gov.dataBreaches, unit: "incidents", label: "Data breaches", dataType: "numeric" });
  }
  if (gov.ethicsTraining != null) {
    dps.push({ tag: "esrs_G1-3-AntiCorruptionTrainingCoverage", value: gov.ethicsTraining, unit: "trainings", label: "Ethics training programs", dataType: "numeric" });
  }

  // Cross-cutting
  if (reportData.crossCutting?.esrs2?.strategy) {
    dps.push({ tag: "esrs_ESRS2SBM1_BusinessModelDescription", value: "Strategy disclosed", label: "Business model description (SBM-1)", dataType: "narrative" });
  }
  if (reportData.crossCutting?.materiality?.irosAssessed != null) {
    dps.push({ tag: "esrs_ESRS2IRO1_DueDiligenceProcess", value: `${reportData.crossCutting.materiality.irosAssessed} IROs assessed`, label: "Due diligence — IROs assessed", dataType: "narrative" });
  }

  return dps;
}
